name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: casonk/.github/.github/workflows/python-ci.yml@main
    with:
      python-versions: '["3.10", "3.12"]'
